# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='question',
            new_name='account',
        ),
    ]
