# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0002_auto_20170613_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='votes',
            new_name='prospect_views',
        ),
    ]
