# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0003_auto_20170614_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='prospect_text',
        ),
        migrations.AddField(
            model_name='prospect',
            name='full_name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
