# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0010_auto_20170615_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
