# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0012_account_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-account_name'], 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterField(
            model_name='account',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='industry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospecting.Account'),
        ),
    ]
