# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0013_auto_20170619_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterField(
            model_name='account',
            name='date_added',
            field=models.DateTimeField(verbose_name='date_added'),
        ),
    ]
