# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0014_auto_20170621_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='industry',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
