# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0015_auto_20170621_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='prospect_website',
            field=models.URLField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
