# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0016_prospect_prospect_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_website',
            field=models.URLField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
